### ISSUE TITLE
[Testing] Create local directory for dumping PDFs / PNGs for testing

### ISSUE THREAD

**Issue by jsbean** [dn-m/GraphicsTools#60]
Currently, [`renderToPDF(name:)`](https://github.com/dn-m/GraphicsTools/blob/master/GraphicsTools/CALayer%2BPDF.swift#L17-L46), attempts to create a directory on my personal computer. Which was a convenient hack, though needs to be dealt with at some point.

**Comment by mossheim** [comment]
It should probably just take a path as an argument, right?

**Comment by jsbean** [comment]
The desire for the feature of saving PDFs / PNGs in this fashion is two-fold:

- Immediate intuitive feedback of results of graphical algorithms (dev-facing)
- Pixel-by-pixel comparison testing

If we just save the files to a test bundle, they kind of just dissipate into the void (without a cumbersome amount of spelunking), we also need to make it trivial to verify the images in process.

**Comment by jsbean** [comment]
Closed by #106. Now we can use [`dn-m/GraphicsTestTools`](https://github.com/dn-m/GraphicsTestTools).
